### ISSUE TITLE
Some updates needed

### ISSUE THREAD

**Issue by iMattPro** [michaelcullum/phpbb-vagrant#1]
This should checkout `master` of phpbb, since the default branch is still 3.1.x, which does not support the CLI installer.

Also the CLI installer is now in `/install/` and not `/install_new/`

**Comment by michaelcullum** [comment]
This is basically a project I never properly finished. If you want to do it, feel free to start it under the phpbb namespace?

**Comment by iMattPro** [comment]
Most of this is too greek for me
